### ISSUE TITLE
new release and documentation correction

### ISSUE THREAD

**Issue by lukadriel7** [rennokki/befriended#27]
Hello, thank you for the great package. I recently added befriended through composer and realized that following didn't work. I checked on the github page and saw that it was an issue that was corrected. I had to manually replace the file to make it work. Since it is a breaking error, maybe a release could help others not search for a long time. Also the documentation features errors in the block and like section. Instead of $user->liking() or $user->blocking() it is written $user->likings() and $user->blockings() which are misleading (I guess a typo mistake).
Again thank you very much for all

**Comment by rennokki** [comment]
Hey @lukadriel7,

It's been pushed, it seems like the pull request messed up the following section of the package. I reverted that, also I fixed the documentation (i also counted consistency), so now the actual relationships remained exactly like that: `blocking()` and `liking()` (without plural).

The PR can be found here: https://github.com/rennokki/befriended/pull/28

Right after the PR passes tests, i will release as a minor since no breaking changes occured.
