### ISSUE TITLE
How can i retrieve a followed user's posts?

### ISSUE THREAD

**Issue by danilogkir** [rennokki/befriended#30]
I've tried with this: 
```
$posts = Post::with('comments')->latest()->get();
$user->following($posts)->get();
```
But it is not working for me, how can i properly do it? 
I've tried other options such as:
```
$user->following()->load('posts');
$user->following()->get()->load('posts');
$user->following()->with('posts');
```

Thanks in advance for the help.

P.D:
I'm trying to retrieve the posts that have the comment relationship on them as you can see:
```
$posts = Post::with('comments')->latest()->get();
```

**Comment by rennokki** [comment]
Hi @danilogkir,

Down each `Following` and `Blocking` sections in the docs you will find a section on how to filter it. For yours, you can use the [followings filter](https://github.com/rennokki/befriended#filtering-followedunfollowed-models).

You want to retrieve a user's followers' posts. To do so, you have to filter what you follow (so you'll get results only people you're following) and then just use the `with()` method to load additional relationships to it:
```php
$me = $request->user(); // example
$followers = User::with('posts')->filterFollowingsOf($me)->get();

foreach ($followers as $follower) {
   foreach ($follower->posts as $post) {
      // logic, or whatever
   }
}
```
Make sure you are using the `Rennokki\Befriended\Scopes\CanFilterFollowingModels` trait to your user.

If you want to load further eager loading, for example, posts & their comments, you can do so by passing `posts.comments` instead of just `posts` in the `with()` method.

**Comment by danilogkir** [comment]
thanks a lot @rennokki 🙌🏻

**Comment by H4ck3r-x0** [comment]
Hi there, How can I retrieve the requester data?
This is my code.
```
      $user = $request->user();
        $followersPost = UserPost::with(['user' => function ($query) use ($user) {
            $query->filterFollowingsOf($user);
        }])->latest()->get();
        return $followersPost;

```
