### ISSUE TITLE
Compatibility with Laravel UUIDs

### ISSUE THREAD

**Issue by muhammedkarayazi** [rennokki/befriended#43]
Hi,

i'm using UUID instead of incrementing ids. I followed this tutorial to implement that mechanism: https://medium.com/@steveazz/setting-up-uuids-in-laravel-5-552412db2088 and keep getting an error while trying to follow someone.

The error message is 
` "message": "SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value (SQL: insert into `followers` (`created_at`, `followable_id`, `followable_type`, `follower_id`, `follower_type`, `updated_at`) values (2019-03-02 10:14:16, 35863b00-2254-11e9-93a9-cf58a7333282, App\\User, d70d84e0-3863-11e9-8d2a-99a5f86ac3ee, App\\User, 2019-03-02 10:14:16))",`

I just inserted my trait to "auto generate uuid" when creating new rows and updated my migratons and models. 

Anyone have an advice how I can implement support for UUIDs?

Best regards

**Comment by rennokki** [comment]
I assume you set up `uuid` as the field for your ID but incrementing is set to `false`. Make sure you drop the primary key on ID and add a new field called `id` or `uuid` where you'll store the UUID and implement in your own Follower model. Within it, make sure you also set protected $primaryKey` to the right field.

In case i did not point well, I need more stacktrace.

**Comment by Chrisx84** [comment]
what rennokki said but if you already merged the tables into your database just change the user id fields from int to varchar or whatever data type your user's id is set as in the laravel user table.
i to am using UUID for user id instead of auto incrementing integer so i just had to change followable_id and follower_id from int(11) to varchar(255) in navicat.
